[colors.bright]
black =   "0x4C566A"
red =     "0xbf616a"
green =   "0xa3be8c"
yellow =  "0xebcb8b"
blue =    "0x81a1c1"
magenta = "0xB48EAD"
cyan =    "0x8FBCBB"
white =   "0xECEFF4"


[colors.normal]
black =   "0xd8dee9"
red =     "0xbf616a"
green =   "0xa3be8c"
yellow =  "0xebcb8b"
blue =    "0x81a1c1"
magenta = "0xB48EAD"
cyan =    "0x88C0D0"
white =   "0xE5E9F0"

[colors.primary]
background = "0xffffff"
foreground = "0x5e81ac"

[font]
size = 14

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Italic"

[font.italic]
style = "Book Italic"

[font.normal]
family = "Operator Mono"
style = "Book"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"

[window.padding]
x = 3
y = 3
