#!/usr/bin/env bash


# on uberpsace
if [ -n "$(hostname | grep uberspace)" ]
then
  # nodejs
  PATH=/package/host/localhost/nodejs-5.1.1/bin:$PATH
  #  ruby
  PATH=/package/host/localhost/ruby-2.2.3/bin:$PATH
fi
