#!/bin/bash
set -e


# macOS development setup
#
# Run this script to install and setup basic tools on a machine.
# Or run it to update current setup to latest changes.
# Steal the bits you like and adjust it to your needs.


# Run in dotfiles folder
cd "$(dirname "${BASH_SOURCE}")"


# Become super user before starting work
sudo -v


printf "\nSetting up system with latest toys ...\n\n"


# Enable italic support
tic xterm-256color-italic.terminfo


# Create folders
mkdir -p \
  ~/bin \
  ~/projects


# Create Symlinks
link_to() {
  if [ ! -e $2 ]
  then
    ln -s $1 $2
    printf "\nLinked $2"
  fi
}
link_dotfile() {
  link_to $(pwd)/$1 ~/.$1
}

link_dotfile inputrc
link_dotfile bashrc
link_dotfile bash_profile
link_dotfile gitconfig
link_dotfile vimrc
link_dotfile psqlrc
link_dotfile sqliterc
link_to $(pwd)/nvim-client ~/bin/nvim-client
link_to ~/Sync/ssh/config ~/.ssh/config


printf "\nUpdating macOS\n"
sudo softwareupdate -i -a


# Brew
printf "\nInstalling Brew formulas\n"
brew update
brew upgrade
brew cleanup
# Install all not installed packages from ./brew.txt
comm -23 <(sort brew.txt) <({ brew ls --full-name; brew cask ls | sed -e 's#^#Caskroom/cask/#'; } | sort) | xargs brew install


# NPM packages
printf "\nUpdating npm packages\n"
npm i -g npm
npm update -g


# Go tools
printf "\nInstalling Go tools"
go get -u github.com/golang/dep
go get -u github.com/davecheney/httpstat
go get -u github.com/christophberger/goman
go get -u github.com/nsf/gocode
go get -u github.com/kisielk/errcheck
go get -u github.com/tj/mmake/cmd/mmake


# Neovim
test -d ~/.vim || mkdir ~/.vim
if [ ! -d ~/.config/nvim ]
then
  ln -s ~/.vim ~/.config/nvim
  ln -s ~/.vimrc ~/.config/nvim/init.vim
  ln -s /usr/share/vim/vim74/spell/ ~/.config/nvim/
  printf "\nLinked Neovim config"
fi

## vim-plug
if [ ! -e ~/.config/nvim/autoload/plug.vim ]
then
  printf "\nInstalling vim-plug"
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  #### YouCompleteMe
  pip install neovim
  cd ~/.config/nvim/plugged/YouCompleteMe && ./install.py --tern-completer
fi
nvim +PlugInstall +PlugUpgrade +PlugUpdate +qall


printf "\n\n\nAll good. Enjoy your day human."

